[package]
name = "zcash_client_sqlite"
description = "An SQLite-based Zcash light client"
version = "0.1.0"
authors = [
    "Jack Grigg <jack@z.cash>",
]
homepage = "https://github.com/zcash/librustzcash"
repository = "https://github.com/zcash/librustzcash"
readme = "README.md"
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
bech32 = "0.7"
bs58 = { version = "0.3", features = ["check"] }
ff = "0.7"
group = "0.7"
jubjub = "0.4"
protobuf = "2"
rand_core = "0.5.1"
rusqlite = { version = "0.23", features = ["bundled"] }
time = "0.1"
zcash_client_backend = { version = "0.3", path = "../zcash_client_backend" }
zcash_primitives = { version = "0.3", path = "../zcash_primitives" }

[dev-dependencies]
rand_core = "0.5.1"
tempfile = "3"
zcash_proofs = { version = "0.3", path = "../zcash_proofs" }

[features]
mainnet = []
