[package]
name = "zcash_client_backend"
description = "APIs for creating shielded Zcash light clients"
version = "0.5.0"
authors = [
    "Jack Grigg <jack@z.cash>",
    "Kris Nuttycombe <kris@electriccoin.co>"
]
homepage = "https://github.com/zcash/librustzcash"
repository = "https://github.com/zcash/librustzcash"
readme = "README.md"
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.56.1"

[dependencies]
base64 = "0.13"
bech32 = "0.8"
bls12_381 = "0.7"
bs58 = { version = "0.4", features = ["check"] }
byteorder = { version = "1", optional = true }
crossbeam-channel = "0.5"
ff = "0.12"
group = "0.12"
hex = "0.4"
hdwallet = { version = "0.3.1", optional = true }
jubjub = "0.9"
log = "0.4"
nom = "7"
orchard = "0.2"
percent-encoding = "2.1.0"
proptest = { version = "1.0.0", optional = true }
protobuf = "~2.27.1" # MSRV 1.52.1
rand_core = "0.6"
rayon = "1.5"
ripemd = { version = "0.1", optional = true }
secp256k1 = { version = "0.21", optional = true }
secrecy = "0.8"
sha2 = { version = "0.10.1", optional = true }
subtle = "2.2.3"
time = "0.2"
tracing = "0.1"
zcash_address = { version = "0.1", path = "../components/zcash_address" }
zcash_encoding = { version = "0.1", path = "../components/zcash_encoding" }
zcash_note_encryption = { version = "0.1", path = "../components/zcash_note_encryption" }
zcash_primitives = { version = "0.7", path = "../zcash_primitives" }

ipfs = { git = "https://github.com/rs-ipfs/rust-ipfs", optional = true }
tokio = { version = "1", features = ["full"], optional = true }
tokio-stream = { version = "0.1", optional = true }

[build-dependencies]
protobuf-codegen-pure = "~2.27.1" # MSRV 1.52.1

[dev-dependencies]
gumdrop = "0.8"
proptest = "1.0.0"
rand_xorshift = "0.3"
tempfile = "3.1.0"
zcash_proofs = { version = "0.7", path = "../zcash_proofs" }

[features]
transparent-inputs = ["ripemd", "hdwallet", "sha2", "secp256k1", "zcash_primitives/transparent-inputs"]
test-dependencies = [
    "proptest",
    "orchard/test-dependencies",
    "zcash_primitives/test-dependencies",
]
unstable = ["byteorder"]
zmail = ["ipfs", "tokio", "zcash_note_encryption/encrypt-to-recipient"]

[lib]
bench = false

[badges]
maintenance = { status = "actively-developed" }
