[package]
name = "zcash_client_backend"
description = "APIs for creating shielded Zcash light clients"
version = "0.4.0"
authors = [
    "Jack Grigg <jack@z.cash>",
]
homepage = "https://github.com/zcash/librustzcash"
repository = "https://github.com/zcash/librustzcash"
readme = "README.md"
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
bech32 = "0.7"
bls12_381 = "0.3.1"
bs58 = { version = "0.3", features = ["check"] }
base64 = "0.12.3"
ff = "0.8"
group = "0.8"
hex = "0.4"
jubjub = "0.5.1"
nom = "5.1.2"
protobuf = "2.20"
rand_core = "0.5.1"
ripemd160 = { version = "0.9.1", optional = true }
secp256k1 = { version = "0.19", optional = true }
sha2 = "0.9"
subtle = "2.2.3"
time = "0.2"
zcash_primitives = { version = "0.4", path = "../zcash_primitives" }
proptest = { version = "0.10.1", optional = true }
percent-encoding = "2.1.0"

[build-dependencies]
protobuf-codegen-pure = "2.20"

[dev-dependencies]
gumdrop = "0.8"
rand_core = "0.5.1"
rand_xorshift = "0.2"
tempfile = "3.1.0"
zcash_client_sqlite = { version = "0.2", path = "../zcash_client_sqlite" }
zcash_proofs = { version = "0.4", path = "../zcash_proofs" }

[features]
transparent-inputs = ["ripemd160", "secp256k1"]
test-dependencies = ["proptest", "zcash_primitives/test-dependencies"]

[badges]
maintenance = { status = "actively-developed" }
